// ============================================================
// SpendLens — POST /api/leads
// Saves lead to Supabase, sends email via Resend.
// Honeypot: if `website` field is filled, silently return 200.
// Rate limiting is handled by middleware.ts.
// ============================================================

import { NextRequest, NextResponse } from 'next/server'
import { Resend } from 'resend'
import { getServiceClient } from '@/lib/supabase'
import type { LeadApiRequest, LeadApiResponse, AuditRow } from '@/lib/types'


function buildEmailHtml(
  audit: AuditRow,
  auditUrl: string,
): string {
  const topRecs = [...audit.results]
    .sort((a, b) => b.potentialMonthlySavings - a.potentialMonthlySavings)
    .slice(0, 3)

  const recsHtml = topRecs
    .map(
      r => `
      <tr>
        <td style="padding: 12px; border-bottom: 1px solid #e5e7eb;">
          <strong>${r.tool}</strong> — ${r.plan}
        </td>
        <td style="padding: 12px; border-bottom: 1px solid #e5e7eb; color: #16a34a; font-weight: 600;">
          $${r.potentialMonthlySavings}/mo saved
        </td>
        <td style="padding: 12px; border-bottom: 1px solid #e5e7eb; color: #4b5563; font-size: 14px;">
          ${r.recommendedAction}
        </td>
      </tr>`,
    )
    .join('')

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 600px; margin: 0 auto; background: #f9fafb; padding: 32px 16px;">
  <div style="background: white; border-radius: 16px; padding: 32px; box-shadow: 0 1px 3px rgba(0,0,0,0.1);">
    
    <div style="text-align: center; margin-bottom: 32px;">
      <h1 style="font-size: 28px; font-weight: 800; color: #111827; margin: 0 0 8px;">
        💸 SpendLens Audit Report
      </h1>
      <p style="color: #6b7280; margin: 0;">Your AI spend analysis is ready</p>
    </div>

    <div style="background: linear-gradient(135deg, #f0fdf4, #dcfce7); border-radius: 12px; padding: 24px; text-align: center; margin-bottom: 32px;">
      <p style="color: #16a34a; font-size: 14px; font-weight: 600; margin: 0 0 8px; text-transform: uppercase; letter-spacing: 0.05em;">Potential Monthly Savings</p>
      <p style="font-size: 48px; font-weight: 800; color: #15803d; margin: 0;">
        $${audit.total_monthly_savings}/mo
      </p>
      <p style="color: #166534; font-size: 16px; margin: 8px 0 0;">
        $${audit.total_annual_savings}/year
      </p>
    </div>

    <h2 style="font-size: 18px; font-weight: 700; color: #111827; margin: 0 0 16px;">Top 3 Recommendations</h2>
    <table style="width: 100%; border-collapse: collapse; margin-bottom: 32px;">
      <thead>
        <tr style="background: #f3f4f6;">
          <th style="padding: 10px 12px; text-align: left; font-size: 12px; color: #6b7280; text-transform: uppercase; letter-spacing: 0.05em;">Tool</th>
          <th style="padding: 10px 12px; text-align: left; font-size: 12px; color: #6b7280; text-transform: uppercase; letter-spacing: 0.05em;">Savings</th>
          <th style="padding: 10px 12px; text-align: left; font-size: 12px; color: #6b7280; text-transform: uppercase; letter-spacing: 0.05em;">Action</th>
        </tr>
      </thead>
      <tbody>${recsHtml}</tbody>
    </table>

    <div style="text-align: center; margin-bottom: 32px;">
      <a href="${auditUrl}" style="display: inline-block; background: #111827; color: white; text-decoration: none; padding: 14px 28px; border-radius: 8px; font-weight: 600; font-size: 16px;">
        View Full Audit Report →
      </a>
    </div>

    ${audit.total_monthly_savings > 500 ? `
    <div style="background: #fefce8; border: 1px solid #fde047; border-radius: 12px; padding: 20px; margin-bottom: 24px;">
      <p style="color: #854d0e; font-weight: 600; margin: 0 0 8px;">💡 Significant savings detected</p>
      <p style="color: #713f12; font-size: 14px; margin: 0;">
        If your audit shows significant savings, a Credex advisor may reach out about accessing these tools at reduced cost through unused enterprise credits.
      </p>
    </div>
    ` : ''}

    <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 24px 0;">
    
    <p style="color: #9ca3af; font-size: 12px; text-align: center; margin: 0;">
      Generated by <strong>SpendLens</strong> — a free AI spend audit tool by 
      <a href="https://credex.rocks" style="color: #6b7280;">Credex</a>.<br>
      Your email is used only to send this report. We don't sell or share it.
    </p>
  </div>
</body>
</html>`
}

export async function POST(
  request: NextRequest,
): Promise<NextResponse<LeadApiResponse | { error: string }>> {
  try {
    const body = (await request.json()) as LeadApiRequest

    // Honeypot check — bots fill all fields
    if (body.website && body.website.trim().length > 0) {
      // Silently return success; do nothing
      return NextResponse.json({ success: true })
    }

    // Validate required fields
    if (!body.email || !body.email.includes('@')) {
      return NextResponse.json({ error: 'Valid email is required' }, { status: 400 })
    }
    if (!body.auditId) {
      return NextResponse.json({ error: 'Audit ID is required' }, { status: 400 })
    }

    const supabase = getServiceClient()

    // Fetch audit to get savings data for email
    const { data: audit, error: auditErr } = await supabase
      .from('audits')
      .select('*')
      .eq('id', body.auditId)
      .single()

    if (auditErr || !audit) {
      return NextResponse.json({ error: 'Audit not found' }, { status: 404 })
    }

    // Save lead
    const { error: leadErr } = await supabase.from('leads').insert({
      audit_id: body.auditId,
      email: body.email,
      company: body.company ?? null,
      role: body.role ?? null,
    })

    if (leadErr) {
      console.error('Lead insert error:', leadErr)
      return NextResponse.json({ error: 'Failed to save lead' }, { status: 500 })
    }

    // Send email via Resend (lazy init to avoid build-time key check)
    const auditUrl = `${process.env.NEXT_PUBLIC_SITE_URL ?? 'https://YOUR_VERCEL_URL'}/audit/${body.auditId}`
    const resend = new Resend(process.env.RESEND_API_KEY)
    await resend.emails.send({
      from: 'SpendLens Audit <audit@resend.dev>',
      to: body.email,
      subject: `Your AI spend audit — $${audit.total_monthly_savings}/mo in potential savings`,
      html: buildEmailHtml(audit as AuditRow, auditUrl),
    })

    return NextResponse.json({ success: true })
  } catch (err) {
    console.error('Leads route error:', err)
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 })
  }
}
